# fbx.pyi
# helps with code completetion, generated using libraries (mypy.stubgen)

from typing import List, Optional, Union, Any, Tuple

# Basic types
class FbxString(str):
    ...

class FbxBool(bool):
    ...

class FbxDouble(float):
    ...

class FbxInt(int):
    ...

# Core types
class FbxManager:
    @staticmethod
    def Create() -> "FbxManager": ...
    def Destroy(self) -> None: ...

    def GetIOSettings(self) -> "FbxIOSettings | None": ...
    def SetIOSettings(self, ios: "FbxIOSettings") -> None: ...

class FbxScene:
    @staticmethod
    def Create(manager: FbxManager, name: Optional[str] = None) -> "FbxScene": ...
    def GetRootNode(self) -> "FbxNode": ...
    def SetCurrentAnimationStack(self, anim_stack: "FbxAnimStack") -> None: ...
    def GetCurrentAnimationStack(self) -> "FbxAnimStack": ...

class FbxNode:
    @staticmethod
    def Create(scene: FbxScene, name: Optional[str] = None) -> "FbxNode": ...
    def AddChild(self, child: "FbxNode") -> None: ...
    def RemoveChild(self, child: "FbxNode") -> None: ...
    def GetChildCount(self) -> int: ...
    def GetChild(self, index: int) -> "FbxNode": ...
    def GetName(self) -> str: ...
    def SetName(self, name: str) -> None: ...
    def SetTranslation(self, x: float, y: float, z: float) -> None: ...
    def SetRotation(self, x: float, y: float, z: float) -> None: ...
    def SetScaling(self, x: float, y: float, z: float) -> None: ...
    def GetNodeAttribute(self) -> FbxNodeAttribute | None: ...
    def GetParent(self) -> "FbxNode | None": ...

# Node Attribute Base
class FbxNodeAttribute:
    class EType:
        eUnknown: int
        eNull: int
        eMarker: int
        eSkeleton: int
        eMesh: int
        eCamera: int
        eLight: int

    def GetAttributeType(self) -> int: ...

# Mesh
class FbxMesh:
    @staticmethod
    def Create(node: FbxNode, name: Optional[str] = None) -> "FbxMesh": ...
    def GetControlPointsCount(self) -> int: ...
    def GetControlPoints(self) -> List[Tuple[float, float, float]]: ...
    def SetControlPoints(self, points: List[Tuple[float, float, float]]) -> None: ...
    def GetPolygonCount(self) -> int: ...
    def GetPolygonVertex(self, polygon_index: int, vertex_index: int) -> int: ...

# Cameras
class FbxCamera:
    @staticmethod
    def Create(node: FbxNode, name: Optional[str] = None) -> "FbxCamera": ...
    def GetName(self) -> str: ...
    def SetName(self, name: str) -> None: ...
    def SetTranslation(self, x: float, y: float, z: float) -> None: ...
    def SetRotation(self, x: float, y: float, z: float) -> None: ...
    def SetFieldOfView(self, fov: float) -> None: ...
    def GetFieldOfView(self) -> float: ...

# Markers
class FbxMarker:
    @staticmethod
    def Create(node: FbxNode, name: Optional[str] = None) -> "FbxMarker": ...
    def GetName(self) -> str: ...
    def SetName(self, name: str) -> None: ...
    def SetTranslation(self, x: float, y: float, z: float) -> None: ...
    def GetTranslation(self) -> Tuple[float, float, float]: ...

# Skeleton / Bones
class FbxSkeleton:
    @staticmethod
    def Create(node: FbxNode, name: Optional[str] = None) -> "FbxSkeleton": ...
    def GetName(self) -> str: ...
    def SetName(self, name: str) -> None: ...
    def GetChildren(self) -> List[FbxNode]: ...

# Animation
class FbxAnimStack:
    @staticmethod
    def Create(scene: FbxScene, name: Optional[str] = None) -> "FbxAnimStack": ...
    def GetName(self) -> str: ...

class FbxAnimLayer:
    @staticmethod
    def Create(scene: FbxScene, name: Optional[str] = None) -> "FbxAnimLayer": ...

class FbxAnimCurve:
    ...

# Importer/Exporter
class FbxImporter:
    @staticmethod
    def Create(manager: FbxManager, name: Optional[str] = None) -> "FbxImporter": ...
    def Initialize(self, filename: str, file_format: int = -1, settings: Optional["FbxIOSettings"] = None) -> bool: ...
    def Import(self, scene: FbxScene) -> bool: ...
    def Destroy(self) -> None: ...

class FbxExporter:
    @staticmethod
    def Create(manager: FbxManager, name: Optional[str] = None) -> "FbxExporter": ...
    def Initialize(self, filename: str, file_format: int = -1, settings: Optional["FbxIOSettings"] = None) -> bool: ...
    def Export(self, scene: FbxScene) -> bool: ...
    def Destroy(self) -> None: ...

class FbxIOSettings:
    @staticmethod
    def Create(manager: FbxManager, name: Optional[str] = None) -> "FbxIOSettings": ...
    def SetBoolProp(self, prop_name: str, value: bool) -> None: ...
    def GetBoolProp(self, prop_name: str) -> bool: ...

