# fbx.pyi
# helps with code completetion, generated using libraries (mypy.stubgen)

from typing import List, Optional, Union, Any, Tuple

# Basic types
class FbxString(str):
    ...

class FbxBool(bool):
    ...

class FbxDouble(float):
    ...

class FbxInt(int):
    ...

class FbxTime:
    """Represents FBX time/frame"""
    def __init__(self, seconds: float = 0.0) -> None: ...
    def SetSecondDouble(self, seconds: float) -> None: ...
    def GetSecondDouble(self) -> float: ...
    def __add__(self, other: "FbxTime") -> "FbxTime": ...
    def __sub__(self, other: "FbxTime") -> "FbxTime": ...


# Manager and Scene
class FbxManager:
    @staticmethod
    def Create() -> "FbxManager": ...
    def Destroy(self) -> None: ...

class FbxScene:
    @staticmethod
    def Create(manager: FbxManager, name: Optional[str] = None) -> "FbxScene": ...
    def GetRootNode(self) -> "FbxNode": ...
    def SetCurrentAnimationStack(self, anim_stack: "FbxAnimStack") -> None: ...
    def GetCurrentAnimationStack(self) -> "FbxAnimStack": ...


# Nodes and Geometry
class FbxNode:
    @staticmethod
    def Create(scene: FbxScene, name: Optional[str] = None) -> "FbxNode": ...
    def AddChild(self, child: "FbxNode") -> None: ...
    def GetChildCount(self) -> int: ...
    def GetChild(self, index: int) -> "FbxNode": ...
    def GetName(self) -> str: ...
    def SetName(self, name: str) -> None: ...
    def GetMesh(self) -> Optional["FbxMesh"]: ...
    def SetTranslation(self, x: float, y: float, z: float) -> None: ...
    def SetRotation(self, x: float, y: float, z: float) -> None: ...
    def SetScaling(self, x: float, y: float, z: float) -> None: ...

class FbxMesh:
    @staticmethod
    def Create(node: FbxNode, name: Optional[str] = None) -> "FbxMesh": ...
    def GetControlPointsCount(self) -> int: ...
    def GetControlPoints(self) -> List[Tuple[float, float, float]]: ...
    def SetControlPoints(self, points: List[Tuple[float, float, float]]) -> None: ...
    def GetPolygonCount(self) -> int: ...
    def GetPolygonVertices(self, index: int) -> List[int]: ...

class FbxSurfaceMaterial:
    ...


# Animation
class FbxAnimStack:
    @staticmethod
    def Create(scene: FbxScene, name: Optional[str] = None) -> "FbxAnimStack": ...
    def GetName(self) -> str: ...

class FbxAnimLayer:
    @staticmethod
    def Create(scene: FbxScene, name: Optional[str] = None) -> "FbxAnimLayer": ...

class FbxAnimCurve:
    ...


# Importer/Exporter
class FbxImporter:
    @staticmethod
    def Create(manager: FbxManager, name: Optional[str] = None) -> "FbxImporter": ...
    def Initialize(self, filename: str, file_format: int = -1, settings: Optional["FbxIOSettings"] = None) -> bool: ...
    def Import(self, scene: FbxScene) -> bool: ...
    def Destroy(self) -> None: ...

class FbxExporter:
    @staticmethod
    def Create(manager: FbxManager, name: Optional[str] = None) -> "FbxExporter": ...
    def Initialize(self, filename: str, file_format: int = -1, settings: Optional["FbxIOSettings"] = None) -> bool: ...
    def Export(self, scene: FbxScene) -> bool: ...
    def Destroy(self) -> None: ...

class FbxIOSettings:
    @staticmethod
    def Create(manager: FbxManager, name: Optional[str] = None) -> "FbxIOSettings": ...
    def SetBoolProp(self, prop_name: str, value: bool) -> None: ...
    def GetBoolProp(self, prop_name: str) -> bool: ...


# Utilities
def FbxLoadScene(manager: FbxManager, path: str) -> Optional[FbxScene]: ...
def FbxSaveScene(manager: FbxManager, scene: FbxScene, path: str) -> bool: ...
